stages:
  - check

variables:
  PDM_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pdm"
  PDM_CHECK_UPDATE: "false"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PDM_VENV_IN_PROJECT: "1"

cache:
  key:
    files:
      - pdm.lock
      - pyproject.toml
  paths:
    - .cache/pdm
    - .venv

check:
  stage: check
  image: python:3.12-bookworm
  before_script:
    - python --version
    - apt-get update
    - apt-get install -y --no-install-recommends nodejs ca-certificates
    - node --version
    - python -m pip install --upgrade pip pdm
    - pdm config python.use_venv true
    - PDM_IGNORE_ACTIVE_VENV=1 pdm install --no-default -G test --no-self --frozen-lockfile
  script:
    - PDM_IGNORE_ACTIVE_VENV=1 pdm run check
