stages:
  - check

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PDM_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pdm"
  PDM_CHECK_UPDATE: "false"
  PDM_VENV_IN_PROJECT: "1"

cache:
  key:
    files:
      - pyproject.toml
      - pdm.lock
  paths:
    - .cache/pip/
    - .cache/pdm/
    - .venv/

check:
  stage: check
  image: python:3.12-bookworm
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends nodejs ffmpeg
    - rm -rf /var/lib/apt/lists/*
    - python -m pip install --upgrade pip pdm
    - pdm --version
    - node --version
    - PDM_IGNORE_ACTIVE_VENV=1 pdm install -G test --frozen-lockfile
  script:
    - PDM_IGNORE_ACTIVE_VENV=1 pdm run check
